### PR TITLE
Add support for mcps prefix

### PR DESCRIPTION
**Pull request by martinp**

### CODE REVIEW

**Comment by falsovsky** [comment]
Can you explain at least what this is ?

**Comment by martinp** [comment]
Of course. [Mircryption](http://www.donationcoder.com/Software/Mouser/mircryption/index.php) is another implementation of FiSH encryption, which uses the same algorithm. However, their prefix defaults to `mcps` instead of `+OK`.

The old FiSH-irssi module supported this prefix as evidenced by the initial commit: https://github.com/falsovsky/FiSH-irssi/commit/2a6f96e011494ad35209620e62b5cff24dc6e3bf#diff-7b42f1885d7f3e26f1e598aec5494547R73

**Comment by martinp** [comment]
Looks like it was removed in db43723b94f7b50c93cbf5f1574ec7cbf2ede922.

**Comment by martinp** [comment]
Any update here?

**Pull request merged**
