### PR TITLE
OpenSSL 1.1 compatibility, one bugfix

### PR DESCRIPTION
**Pull request by dogo42**
Added OpenSSL 1.1 API compatibility. Fix segfault when user tries /keyx <something> and there is no connection to a server.

### CODE REVIEW

**Comment by falsovsky** [comment]
Hi there,

Is there really a need for using the new API ? Will the older way stop working ?

I aprove the /keyx segfault fix.

**Comment by duritong** [comment]
This patch helped me to get it compiled on a recent Fedora, otherwise I would get:

```
$ make -j4
Scanning dependencies of target fish
[ 28%] Building C object src/CMakeFiles/fish.dir/blowfish.c.o
[ 28%] Building C object src/CMakeFiles/fish.dir/base64.c.o
[ 42%] Building C object src/CMakeFiles/fish.dir/inifile.c.o
[ 57%] Building C object src/CMakeFiles/fish.dir/DH1080.c.o
[ 71%] Building C object src/CMakeFiles/fish.dir/FiSH.c.o
[ 85%] Building C object src/CMakeFiles/fish.dir/password.c.o
/builddir/build/BUILD/FiSH-irssi-71b94ea20f3c454a1b6f0524bbeb6324639f4a42/src/DH1080.c: In function 'DH1080_Init':
/builddir/build/BUILD/FiSH-irssi-71b94ea20f3c454a1b6f0524bbeb6324639f4a42/src/DH1080.c:46:13: error: dereferencing pointer to incomplete type 'DH {aka struct dh_st}'
         g_dh->p = BN_bin2bn(prime1080, DH1080_PRIME_BYTES, NULL);
             ^~
make[2]: *** [src/CMakeFiles/fish.dir/build.make:135: src/CMakeFiles/fish.dir/DH1080.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:86: src/CMakeFiles/fish.dir/all] Error 2
make: *** [Makefile:128: all] Error 2
```

**Comment by falsovsky** [comment]
Hi.

I just tried it on: Fedora release 25 (Twenty Five)

And it works correctly.

**Comment by duritong** [comment]
Yes, Fedora 25 still has 1.0.2j, while the new upcoming F26 (Rawhide atm) has 1.1.0d and this one breaks.

**Pull request merged**
